# ============
# Builder
# ============
FROM golang:1.18.3 as Builder

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

WORKDIR /usr/app/src

COPY go.mod go.sum ./
RUN go mod download

COPY src /usr/app/src/

RUN go build \
    -o /usr/app/bin/main \
    -ldflags '-s -w'


# ============
# Deploy
# ============
FROM gcr.io/distroless/base-debian10

COPY --from=Builder /usr/app/bin/main /app/main

EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/app/main"]