version: "3.8"

services:
  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: "./src"
        target: "/go/app/src"
